package com.model.pojos;
// Generated 12-jun-2016 20:44:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private int numHabitacion;
     private Tipohabitacion tipohabitacion;
     private Set reservacions = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(int numHabitacion) {
        this.numHabitacion = numHabitacion;
    }
    public Habitacion(int numHabitacion, Tipohabitacion tipohabitacion, Set reservacions) {
       this.numHabitacion = numHabitacion;
       this.tipohabitacion = tipohabitacion;
       this.reservacions = reservacions;
    }
   
    public int getNumHabitacion() {
        return this.numHabitacion;
    }
    
    public void setNumHabitacion(int numHabitacion) {
        this.numHabitacion = numHabitacion;
    }
    public Tipohabitacion getTipohabitacion() {
        return this.tipohabitacion;
    }
    
    public void setTipohabitacion(Tipohabitacion tipohabitacion) {
        this.tipohabitacion = tipohabitacion;
    }
    public Set getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set reservacions) {
        this.reservacions = reservacions;
    }




}


