package com.pojos;
// Generated 05-abr-2015 14:44:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Citas generated by hbm2java
 */
public class Citas  implements java.io.Serializable {


     private int idCita;
     private Medico medico;
     private Paciente paciente;
     private Date horaCita;

    public Citas() {
    }

	
    public Citas(int idCita, Medico medico, Paciente paciente) {
        this.idCita = idCita;
        this.medico = medico;
        this.paciente = paciente;
    }
    public Citas(int idCita, Medico medico, Paciente paciente, Date horaCita) {
       this.idCita = idCita;
       this.medico = medico;
       this.paciente = paciente;
       this.horaCita = horaCita;
    }
   
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getHoraCita() {
        return this.horaCita;
    }
    
    public void setHoraCita(Date horaCita) {
        this.horaCita = horaCita;
    }




}


